language: c
sudo: required
compiler:
 - gcc
 - clang
matrix:
  include:
    - os: linux
      dist: trusty
    - os: linux
      dist: precise
    - os: osx
      osx_image: xcode7.2
addons:
 apt:
  packages:
   - autoconf
   - automake
   - bison
   - docbook
   - docbook-xml
   - docbook-xsl
   - gcc
   - libgnutls-dev
   - libhiredis-dev
   - libicu-dev
   - libmemcached-dev
   - libreadline-dev
   - libtool
   - libwrap0-dev
   - libxslt1-dev
   - make
   - pkg-config
   - tcl8.5
   - xsltproc
before install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install pkg-config icu4c; fi
before_script:
 - ./buildconf.sh
script:
 - ./configure && make && make check
