language: c
sudo: required
compiler:
 - gcc
matrix:
  include:
    - os: linux
      dist: trusty
    - os: linux
      dist: precise
addons:
 apt:
  packages:
   - autoconf
   - automake
   - bison
   - docbook
   - docbook-xml
   - docbook-xsl
   - gcc
   - libgnutls-dev
   - libhiredis-dev
   - libicu-dev
   - libmemcached-dev
   - libreadline-dev
   - libtool
   - libwrap0-dev
   - libxslt1-dev
   - make
   - pkg-config
   - tcl8.5
   - xsltproc
before_script:
 - ./buildconf.sh
script:
 - ./configure && make && make check
